### ISSUE TITLE
InstanceState class not serializable

### ISSUE THREAD

**Issue by bekiroguz** [merlijn/kagera#15]
This is a problem when used with cluster setup with multiple nodes.

2017-02-02 15:04:51,470 [DOCA-akka.actor.default-dispatcher-18] [] ERROR akka.remote.EndpointWriter - Failed to serialize remote message [class io.kagera.akka.actor.PetriNetInstanceProtocol$Instanc
eState] using serializer [class akka.serialization.JavaSerializer]. Transient association error (association remains live)
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class io.kagera.akka.actor.PetriNetInstanceProtocol$InstanceState] using serializer [class akka.serializati
on.JavaSerializer].
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:61)
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:895)
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:895)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:894)
        at akka.remote.EndpointWriter.writeSend(Endpoint.scala:786)
        at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:761)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:452)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.NotSerializableException: scala.collection.immutable.MapLike$$anon$2
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply$mcV$sp(Serializer.scala:288)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:288)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:288)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at akka.serialization.JavaSerializer.toBinary(Serializer.scala:288)
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:47)
        ... 17 common frames omitted

**Comment by merlijn** [comment]
This is probably the cause:

http://stackoverflow.com/questions/17709995/notserializableexception-for-mapstring-string-alias
https://issues.scala-lang.org/browse/SI-7005

Called here: https://github.com/merlijn/kagera/blob/dae0f8db8570a74a1dfbcff1314ae993fd9a9412/akka/src/main/scala/io/kagera/akka/actor/PetriNetInstanceProtocol.scala#L141
